
" Vim power
set nocompatible
" Enable syntax colors
syntax enable
" Tab spacing
set tabstop=4
" Line numbers
set number
" Highlight current line
set cursorline
" Show cursor position
set ruler
" Allow cursor keys in insert mode
set esckeys
" Allow backspacing over everything in insert mode
set backspace=indent,eol,start
" Always show status line
set laststatus=2
" Enable mouse in all modes
set mouse=a
" Disable error bells
set noerrorbells
" Don’t reset cursor to start of line when moving around.
set nostartofline
" Start scrolling three lines before the horizontal window border
set scrolloff=3
" Show current mode
set showmode
" Show the filename in the window titlebar
set title
" Show the (partial) command as it’s being typed
set showcmd
" Command-line completion
set wildmenu


" Highlight searches
set hlsearch
" Highlight and search while typing
set incsearch
" Ingore case, unless I use it
set ignorecase
set smartcase
" Maps backspace to clear last search highlighting
" turned off by default incase you like backspace, <BS>
nmap <silent> <BS> :nohlsearch<CR>

" Solarized theme colors
if has('gui_running')
    set background=light
else
    set background=dark
endif
colorscheme solarized

" Change mapleader
let mapleader=","

" Toggle line numbers
nnoremap <leader>l :set invnumber<CR>
" Save a file as root (,W)
nnoremap <leader>W :w !sudo tee % > /dev/null<CR>

" Strip trailing whitespace (,ss)
function! StripWhitespace()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    :%s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfunction
nnoremap <leader>ss :call StripWhitespace()<CR>

augroup perl
    " autoindent
    autocmd FileType perl set autoindent
    autocmd FileType perl set smartindent

    " make lines longer than 120 characters errors (including newline)
    "autocmd FileType perl match ErrorMsg /\%>119v.\+/

    " make tabs and trailing spaces errors
    autocmd FileType perl 2match ErrorMsg /[\t]\|\s\+\%#\@<!$/

augroup END

" Automatic commands
if has("autocmd")
    " Enable file type detection
    filetype on
    " Treat .json files as .js
    autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
    " Treat .md files as Markdown
    autocmd BufNewFile,BufRead *.md setlocal filetype=markdown
endif
